Data split into training (915 samples), validation (114 samples), and testing (114 samples) sets.
Number of classes: 6
Feature data normalized using z-score normalization.
Training:   0%|▌                                                                                                                        | 5/1000 [00:01<03:59,  4.16epoch/s, Train Acc=0.385, Val Acc=0.396]/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py:229: RuntimeWarning: overflow encountered in exp
Epoch: 0 	Train:[Loss: 1.9594, Acc: 0.2448] 	Val:[Loss: 2.2095, Acc: 0.3333]
  return (np.exp(x)/np.sum(np.exp(x), axis=-1, keepdims=True))
/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py:229: RuntimeWarning: invalid value encountered in divide
  return (np.exp(x)/np.sum(np.exp(x), axis=-1, keepdims=True))
Training:  30%|████████████████████████████████████▎                                                                                    | 300/1000 [01:19<03:05,  3.78epoch/s, Train Acc=0.00781, Val Acc=0]
Epoch: 128 	Train:[Loss: nan, Acc: 0.0078] 	Val:[Loss: nan, Acc: 0.0000]
Epoch: 256 	Train:[Loss: nan, Acc: 0.0078] 	Val:[Loss: nan, Acc: 0.0000]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 51, in <module>
    run(setup())
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 45, in run
    model.train(epochs=params["epoch"])
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 438, in train
    train_loss, train_acc = self.train_step(train_loader)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 416, in train_step
    self.backward()
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 398, in backward
    self.dW.append(np.mean(dw, axis=0))
  File "/home/autrio/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 3380, in _mean_dispatcher
    def _mean_dispatcher(a, axis=None, dtype=None, out=None, keepdims=None, *,
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 51, in <module>
    run(setup())
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 45, in run
    model.train(epochs=params["epoch"])
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 438, in train
    train_loss, train_acc = self.train_step(train_loader)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 416, in train_step
    self.backward()
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 398, in backward
    self.dW.append(np.mean(dw, axis=0))
  File "/home/autrio/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 3380, in _mean_dispatcher
    def _mean_dispatcher(a, axis=None, dtype=None, out=None, keepdims=None, *,
KeyboardInterrupt
