Data split into training (915 samples), validation (114 samples), and testing (114 samples) sets.
Number of classes: 6
Feature data normalized using z-score normalization.
Training:   0%|                                                                                                                                                                 | 0/1000 [00:00<?, ?epoch/s]/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py:221: RuntimeWarning: overflow encountered in exp
  return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py:221: RuntimeWarning: invalid value encountered in divide
  return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
Training:   0%|                                                                                                                            | 1/1000 [00:00<04:19,  3.86epoch/s, Train Acc=0.0234, Val Acc=0]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 51, in <module>
    run(setup())
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 45, in run
    model.train(epochs=params["epoch"])
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 444, in train
    tqdm.write(f"Epoch: {epoch} \tTrain:[Loss: {train_loss:.4f}, Acc: {train_acc:.4f}] \tVal:[Loss: {val_loss:.4f}, Acc: {val_acc:.4f}]")
TypeError: unsupported format string passed to numpy.ndarray.__format__
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 51, in <module>
    run(setup())
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/2.py", line 45, in run
    model.train(epochs=params["epoch"])
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 444, in train
    tqdm.write(f"Epoch: {epoch} \tTrain:[Loss: {train_loss:.4f}, Acc: {train_acc:.4f}] \tVal:[Loss: {val_loss:.4f}, Acc: {val_acc:.4f}]")
TypeError: unsupported format string passed to numpy.ndarray.__format__
